server:
  port: 8080 # Replace with 0

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 251084
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: true
        show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: true
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          #jwk-set-uri: http://localhost:9000/.well-known/jwks.json
eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

logging:
  level:
    org:
      springframework: INFO